### ISSUE TITLE
Redundant str() calls in attributes_filter.py

### ISSUE THREAD

**Issue by Abercus** [pm4py/pm4py-source#100]
There are two calls to built-in function str(), which have no effect on the code.

https://github.com/pm4py/pm4py-source/blob/687fca4ba920ab783c3b00089948dacb67679799/pm4py/algo/filtering/log/attributes/attributes_filter.py#L439

https://github.com/pm4py/pm4py-source/blob/687fca4ba920ab783c3b00089948dacb67679799/pm4py/algo/filtering/log/attributes/attributes_filter.py#L507

**Comment by s-j-v-zelst** [comment]
It seems that this is fixed in c57be12

**Comment by s-j-v-zelst** [comment]
we will close the ticket
