### ISSUE TITLE
redesign process tree

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4py/pm4py-source#11]
The process tree class should also describe classes for the operators (not only for the tree itself).
We should try to fix this asap, i.e. before building on top of this too much.

**Comment by Javert899** [comment]
Hi,

The requested feature is now present in the 'ptEnhancement' branch

A class has been associated to each operator, and it is possible to generate a log from the language of the process tree simply doing tree.generate_log()

Anything else important to integrate in the enhancement?
