### ISSUE TITLE
Wrong edge value in heuristic net for edges in length-two loops

### ISSUE THREAD

**Issue by segasp5** [pm4py/pm4py-source#112]
In the file https://github.com/pm4py/pm4py-source/blob/master/pm4py/objects/heuristics_net/net.py in the loop where you deal with length-two graph loops (lines 195-226) the declaration of 'repr_value' variable is missing. The variable is also declared in the previous loop (line 183), so that value is used.

Version: 1.2.0.1

**Comment by Javert899** [comment]
The issue has been solved in hotfix release 1.2.1
