### ISSUE TITLE
Incompatibility with Python 3.5

### ISSUE THREAD

**Issue by Javert899** [pm4py/pm4py-source#114]
Due to the added dependency "extratools", PM4Py has become incompatible with Python 3.5 since release 1.1.28.

**Comment by fit-alessandro-berti** [comment]
Compatibility with Python 3.5 will be fixed for next release (1.2.5)

**Comment by fit-alessandro-berti** [comment]
Just another stuff: for Python releases < 3.6, we needed to force a version of Matplotlib <= 3.0.3, since Matplotlib has recently dropped support for Python 3.5

**Comment by fit-alessandro-berti** [comment]
Closed in 1.2.5
