### ISSUE TITLE
Loading Multiple CSVs

### ISSUE THREAD

**Issue by seanlaw** [pm4py/pm4py-source#117]
I was looking through some of the documentation and I can see that there's a way to load CSVs and dealing with a single large dataset. However, my data is large and split across 400 CSVs. Rather than concatenating them, is there a way to build a process model without loading all of the data into memory? And, instead, do multiple passes over the data even if it requires I/O?

**Comment by fit-alessandro-berti** [comment]
In the PM4Py-Distr project, we are setting up a distributed engine with PM4Py, that is able to run on several cores, and also different machines. The original dataset is a distributed Parquet dataset, that is split among the different workers.

**IMPORTANT**: each file is supposed to contain the complete data about a process execution. That means, events of the same case ID are in the same file, not in different!

Each worker then loads one-by-one the Parquet files, and concatenates the result of the operation back. If each file of your dataset is organized in a way the events of the same case ID are in the same file, **then the same approach can be applied to CSV**.

For example, the code for the calculation of the DFG, that you can find in pm4pydistr.handlers.parquet , is:

    overall_dfg = Counter()
    count = 0
    for index, pq in enumerate(parquet_list):
        pq_basename = Path(pq).name
        if pq_basename in managed_logs:
            count = count + 1
            df = get_filtered_parquet(pq, columns, filters, use_transition=use_transition, parameters=parameters)
            dfg = Counter(
                df_statistics.get_dfg_graph(df, activity_key=activity_key, sort_timestamp_along_case_id=False, sort_caseid_required=False))
            overall_dfg = overall_dfg + dfg
            if count >= no_samples:
                break

**Comment by fit-alessandro-berti** [comment]
In general, if events of the same case ID are split inside different CSVs, we don't provide an utility yet.

But stay tuned :)

**Comment by seanlaw** [comment]
Yes, all of my case ids are contained within the same file (though, I have many, many files). Does it matter if the same user is associated with multiple case ids (where, say, each case id corresponds to completely unrelated times/dates/sessions)?

To be clear, my original question above was more concerned with the fact that I have close to 1 TB of files that cannot be held in memory all at once. So, I was hoping that there was a solution for building a single process model using the Inductive miner that might, say, update the model as new data is seen. I've experienced this kind of approach in the scikit-learn package where they allow a running `partial_fit`. I hope this is clear and that what you described above doesn't require loading all of the data into memory since this initial phase is a test and I will likely double or quadruple the size of the input data later.

**Comment by fit-alessandro-berti** [comment]
In PM4Py we offer the Inductive Miner Directly Follows that operates on the DFG

The script loads the CSVs one by one and transforms that in the specified set of Parquet files. 
However, I did the assumption thst events of the same case can be contained in several files

Within your context, you can simply import the single CSVs using the Pandas adapter (that parses the timestamps also) and export them using the Parquet exporter of PM4Py. Doing tjis operation for all the files you can get a distributed Parquer dataset. Small notes:
- the case ID, activity and timestamp column in such files must be named case:concept:name, concept:name and time:timestamp respectively
- the sort inside a single file shall be done with the following criteria: case ID, then timestamp.

When these conditions are satisfied, PM4Py-Distr works like a rocket. Once we extracted the DFG over a 1.5 billion events log in 40s

**Comment by fit-alessandro-berti** [comment]
However, I must be very clear that managing 1TB of log file within a single machine is very challenging. For working at such sizes with reasonable speed, you would need to setup a PM4Py-Distr cluster enough big

**Comment by seanlaw** [comment]
Thank you. That's good to hear. I haven't played with any of the PM4PY code yet as I just started reading the documentation last night so your response is very reassuring.

I am on a server with 128GB RAM and 8 cores. Let's close this for now and I will try what you've suggested and report back if I run into any problems. Thanks again for your help!

**Comment by fit-alessandro-berti** [comment]
Then it is good to go with 1 master and 7 slave nodes of Pm4py-Distr.. However, that is not so big, for a log with 1.5B events it may take 1500s just to calculate the DFG from the distributed Parquet dataset

**Comment by seanlaw** [comment]
Is there a way to pass special pandas `read_csv` parameters to `transform_csv_dataset_to_parquet_distr_dataset`? I use a special character instead of a comma for delimiting my files and they use an encoding that is different from `utf-8`

**Comment by fit-alessandro-berti** [comment]
So, I updated the utility. First of all, if you tell me that all the events of the same case are in the same CSV file, then you can use the following faster utility. I added (also for the one that you were trying to use) support for the specification of the encoding/quotechar/separator.

Please update to pm4pydistr==0.1.16 (pip install --no-cache-dir -U pm4pydistr==0.1.16)

The new faster utility for your case is:

from pm4pydistr.util import csv_dataset_to_parquet_distr_dataset

csv_dataset_to_parquet_distr_dataset.transform_simple("roadtraffic2", "roadtraffic3", activity_key="concept:name",
                                                      timestamp_key="time:timestamp", caseid_key="case:concept:name",
                                                      parameters={"sep": ";"})

In this case, you can specify the columns as yesterday, and inside the parameters specify: sep, quotechar, encoding, timest_columns (the columns of the file that contains timestamps), timest_format.

If you find your local installation is too small, we have also a docker image, that can be retrieved through * docker pull javert899/pm4pydistr:cloud_docker * that can be used on Google Cloud. I suggest for your case a configuration with 96 cores of the 7th generation or 80 cores of the 9th. However, costs of the analysis may be high.

In the case you feel you need help,
our group (Fraunhofer FIT), with the goal of promoting the process mining activities, offers the possibility to do a quick scan analysis of your logs, including activities like pre-processing, identification of the interesting analysis and performing some of these analysis on the data. For further information about such quick scan analysis, you can consult the site [https://www.fit.fraunhofer.de/en/fb/risk/process-mining/process-mining-quick-scan.html](url)

**Comment by seanlaw** [comment]
Great. Thanks for letting me know. Unfortunately, I don't have that kind of budget but I will keep it in mind. Are there end-to-end examples, Jupyter notebooks, or certain publications that you'd recommend for reading?
