### ISSUE TITLE
How to install the library ?

### ISSUE THREAD

**Issue by serkserk** [pm4py/pm4py-source#12]
Hi,

Im trying to find an alternative to bupaR in python and I found this one which seem quite complete but I can't figure out how to install the library. 
I downloaded the zip but there no setup.py and running the requirements.txt only install the needed library.
Any help ?

Thanks

**Comment by Javert899** [comment]
No install is present yet. At the moment, you could test the library by creating a script in the root directory of the project, including the modules you need

**Comment by serkserk** [comment]
OK, I will do it like that way then, thank you
