### ISSUE TITLE
(Severe) Bug(s) in Process Tree to Petri nets

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4py/pm4py-source#120]
It seems that the process tree to PN has some bugs.
Consider the example PT and corresponding net
![tree](https://user-images.githubusercontent.com/6236151/67227374-72540b80-f437-11e9-81a2-fb0f4e618422.png)
![net](https://user-images.githubusercontent.com/6236151/67227375-72eca200-f437-11e9-9b6e-fe8daa3128d5.png)

The net describes the sequence <a,b,e>, which is definitely not in the language of the model.

I'll try to fix this tomorrow.
However, note that these type of bugs are very severe, and, that testing on a functional level, i.e., does the code actually do what we want it to do? is needed.
This could be related to the change of the loop operator to having two nodes, at the same time, why both c,g and f are skippable in the model is a complete mistery to me.

**Comment by fit-alessandro-berti** [comment]
Yes that is related to having only 2 childs.
The fix is just a change to the boolean value. 

Sorry, that part was not used by ages since the times of the old IMDFA

**Comment by fit-alessandro-berti** [comment]
Proposed fix with refactoring:

![image](https://user-images.githubusercontent.com/56342194/67262820-63f10880-f4a6-11e9-9452-b9b1dff7b3ff.png)
