### ISSUE TITLE
Incorrect precision and replay fitness results of inductive miner

### ISSUE THREAD

**Issue by caoyukun0430** [pm4py/pm4py-source#123]
Hi,
I am Yukun, recently I am generating petri net with inductive miner, and then calculate precision with ETC conformance. The result is not correct comparing with ProM 6.9 "check conformance using ETConformance".
 I use dataset BPIC2017 as original log and generate petri net from its sublog (filtered traces with case attribute value: CreditScore 598). And then, precision is calculated via this petri net and original log. 

The petri net for this sublog looks like below:
![1](https://user-images.githubusercontent.com/46762174/67574320-7edbab00-f73a-11e9-9e7d-8a0adfee7781.jpg)

As the model is simple and "overfit", the precision w.r.t original log should be 1.0. And ProM 6.9 "check conformance using ETConformance" returns me precision result 1.0.
But pm4py shows me:
precision_inductive= 0.9865618203111929

Same story for replay fitness. I use "replay a log on petri net for conformance analysis" in ProM 6.9 and trace fitness result is 0.8. 
But pm4py gives me: fitness_inductive= {'perc_fit_traces': 38.06309988089956, 'average_trace_fitness': 0.9215316861665569, 'log_fitness': 0.9333293300155021}

Below is the code I use for pm4py and I also attached the 2 logs I used.

log = xes_importer.apply(
        "D:\\Sisc\\19SS\\thesis\\Dataset\\BPIC2017\\filteredbpic2017.xes")
sublog = xes_importer.apply(
        "D:\\Sisc\\19SS\\thesis\\Dataset\\BPIC2017\\sublog_598.xes")
inductive_petri, inductive_initial_marking, inductive_final_marking = inductive_miner.apply(sublog)
fitness_inductive = replay_factory.apply(log, inductive_petri, inductive_initial_marking, inductive_final_marking)
print("fitness_inductive=", fitness_inductive)
precision_inductive = precision_factory.apply(log, inductive_petri, inductive_initial_marking,
                                                  inductive_final_marking)
print("precision_inductive=", precision_inductive)

#
[logs.zip](https://github.com/pm4py/pm4py-source/files/3772282/logs.zip)

**Comment by fit-alessandro-berti** [comment]
For fitness PM4Py is right, just look at the variants of the BPI Challenge 2017 Offer inside the demo machine 80.211.142.26

Just looking at the first two variants, you understand that fitness is below 0.5

It depends on your settings in ProM

**Comment by fit-alessandro-berti** [comment]
For precision: it depends on the internal working of the token based replay

If for activating a trace prefix, the insertion of missing tokens is needed, then the behavior in the model is larger than the behavior of the log

Hence also the precision provided by PM4Py is correct

**Comment by fit-alessandro-berti** [comment]
Any difference you see between the ProM ETConformance and the PM4Py ETConformance is in PM4Py favor. This ETConformance in ProM is completely wrong with regards to measuring precision in models containing invisibles. The heuristics used there simply are not able to capture all the behavior allowed in the model. You can check it manually

**Comment by fit-alessandro-berti** [comment]
If you instead were talking about the two 'trace fitness' values, and not the fitness percentage, then the formulas between alignments and token based replay are just different

You can get the same value in PM4Py by using the variant='alignments' of the replay fitness factory

**Comment by fit-alessandro-berti** [comment]
Updates on precision:

- An additional "cleaning_token_flood" parameter has been added for the classical ETConformance approach. This approach is able to detect which tokens during the replay are "superfluous", frozing them and avoiding the activation of unwanted parts of the process model. The default value is kept False. The approach is described in "Reviving Token-based Replay: Increasing Speed While Improving Diagnostics".

- A variant based on alignments has been added to the ETConformance. This shall be more precise because it is not based on the heuristics of the token based replay, and the results comparable with the Align-ETConformance of ProM

**Comment by fit-alessandro-berti** [comment]
As update, my initial assessment was wrong. Indeed in the current version, the replay stops immediately when it is impossible to replay the trace.

Hence, unfit prefixes are not counted in the precision as-is-now

**Comment by fit-alessandro-berti** [comment]
I close this. We may re-discuss the concept later
