### ISSUE TITLE
Wrong model generated by inductive miner

### ISSUE THREAD

**Issue by caoyukun0430** [pm4py/pm4py-source#124]
Hi,
I am Yukun and I observe wrong model generated by inductive miner from pm4py.

Here is the log I use which contains 2 variants:
![image](https://user-images.githubusercontent.com/46762174/67687563-c8293600-f998-11e9-97c3-a7868edb1999.png)
And Obviously it contains one XOR choice and the model generated by ProM 6.9 shows this:
![image](https://user-images.githubusercontent.com/46762174/67687623-e2fbaa80-f998-11e9-81be-0c1eba0eab99.png)

However, when I use pm4py inductive miner, it shows me this model with two slient transitions and allows extra behaviors:
![ind](https://user-images.githubusercontent.com/46762174/67687756-13434900-f999-11e9-9080-7c7e798771b4.png)

Could you please take a look into this? And I will attach the log I use.

Thank you for your help.

Best,
Yukun
[log_3_0_dfg.zip](https://github.com/pm4py/pm4py-source/files/3779185/log_3_0_dfg.zip)

**Comment by fit-alessandro-berti** [comment]
This problem is known.

The maximization of the sequential cut is the approach that was originally followed by Inductive Miner, and that cut is chosen because the number of arcs is maximized

From a later version of Inductive in ProM, the sequential cut detection has changed and it does not maximize anymore the cut but tries to minimize the number of invisibles

Here we follow original version, and in that regards this is correct

**Comment by fit-alessandro-berti** [comment]
I proposed a fix for this long-term problem.

In a sequential cut, the components that share exactly the same input and output arcs are now merged into one. That shall cover exactly this problem without having issues elsewhere:

![tmphvwfz2cl gv](https://user-images.githubusercontent.com/56342194/67751091-c448f280-fa30-11e9-935e-f344eb19fb13.png)

**Comment by caoyukun0430** [comment]
> I proposed a fix for this long-term problem.
> 
> In a sequential cut, the components that share exactly the same input and output arcs are now merged into one. That shall cover exactly this problem without having issues elsewhere.
> 
> You can find the fix in the 'develop' branch
> 
> ![tmphvwfz2cl gv](https://user-images.githubusercontent.com/56342194/67751091-c448f280-fa30-11e9-935e-f344eb19fb13.png)

Hi Ale, 
Thank you for fixing the long-term problem. Now the model is in line with ProM to me now. :)
