### ISSUE TITLE
Branch `decisionTreeIntegration` does not exist 

### ISSUE THREAD

**Issue by visahak** [pm4py/pm4py-source#125]
I want to try the Beta feature with regards to clustering. I wanted to checkout the ‘decisionTreeIntegration’ branch.  The branch does not exist.

**Comment by fit-alessandro-berti** [comment]
Dear visahak,

We are renewing the documentation on the site, so at the moment some updates are missing.

The 'decisionTreeIntegration' branch has been moved to a separate project named pm4py-clustering that is located in the repository https://github.com/Javert899/pm4py-clustering . You could also retrieve that with "pip install -U pm4pyclustering".

Then, you can use the methods described in the documentation replacing the package name "pm4py" with "pm4pyclustering"

**Comment by simpsonskidrock** [comment]
Hello! 

I was wondering if the BETA function of concept drift detection moved to some other place aswell - can you give me an update on that? 

Thank you!

**Comment by fit-alessandro-berti** [comment]
Dear simpsonskidrock ,

You can look at the following pages in the documentation:
http://pm4py.pads.rwth-aachen.de/decision-trees/
http://pm4py.pads.rwth-aachen.de/decision-mining/
