### ISSUE TITLE
Inductive Miner ignores empty traces

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4py/pm4py-source#16]
The inductive miner ignores empty traces
For example, simple log [<>, <a,b>] results in ->(a,b), yet it sould result in x(tau,->(a,b)) (double checked in ProM)

**Comment by Javert899** [comment]
Hi,

The problem is surely solvable in the way you told

But this would also cause some problems in the alignments, where a 'best worst' cost would be calculated to be 0 (because you can reach the final marking without passing from any visibile transition)

It is worthy to produce such a model?

**Comment by s-j-v-zelst** [comment]
Yes, we have to follow the algorithm as specified in the paper.
The problem you mention is a valid one, yet we should never alter discovery algorithms to cope with properties of another algorithm (in this case conformance checking).
Furthermore, by ignoring the trace, we invalidate the perfect replay-fitness property of the inductive miner (regardless of what specific algorithm we use to compute replay-fitness)
