### ISSUE TITLE
Inductive Miner generates flower

### ISSUE THREAD

**Issue by FrankBGao** [pm4py/pm4py-source#17]
I use inductive Miner on the log which has loop. But, it generated a flower in model.
![pm4py](https://user-images.githubusercontent.com/20436775/48148274-acc1a880-e2b9-11e8-8a5d-82ee08153af5.JPG)
And Prom's  result is not, (directly follows graph->Process Tree->Petri Net)
![prom](https://user-images.githubusercontent.com/20436775/48148295-b5b27a00-e2b9-11e8-839c-51062b836f77.JPG)
Here is the log
[log.zip](https://github.com/pm4py/pm4py-source/files/2558468/log.zip)

**Comment by Javert899** [comment]
Set-up issue.
If you look inside pm4py\algo\discovery\inductive\util\shared_constants.py you find several constants for the loop detection.

If you change LOOP_CONST_1 from 0.2 to 0.09, you get the following process schema that is perfectly fit according to the log:

![setup1](https://user-images.githubusercontent.com/41383598/48190488-2b165d00-e343-11e8-82f5-1c2c5d4f394f.png)

Alternatively, if you keep LOOP_CONST_1 as 0.2, and you change LOOP_CONST_4 from -0.7 to -0.15, you get the process schema you expected:

![setup2](https://user-images.githubusercontent.com/41383598/48190679-9d873d00-e343-11e8-8136-8fcaac08e88d.png)

That is also perfectly fit according to the log.
