### ISSUE TITLE
Log: sort function refactor

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4py/pm4py-source#21]
The sort function of the log should appropriately reflect the sort function on an arbitrary list.
Currently it integrates specific event log knowledge and always assumes that the key is applied on event level (which is not necessarily the case).

The lambda function currently in the call to the underlying sort function should be provided by the user.

**Comment by Javert899** [comment]
Hi,

In the 'develop' branch, the sort function by timestamp has been moved into a separate class contained in the 'util'

Moreover, to the same class, sorting functions by lambda expressions have been added.
