### ISSUE TITLE
Import CSV 

### ISSUE THREAD

**Issue by hadisotudeh** [pm4py/pm4py-source#24]
Hi,

I get the following error when I import a CSV file.
KeyError: 'concept:name'

My code:
```
from pm4py.objects.log.importer.csv import factory as csv_importer

event_log = csv_importer.import_log('grouped/'+file_name)

from pm4py.objects.log import transform

trace_log = transform.transform_event_log_to_trace_log(event_log,case_glue="caseID")

net, initial_marking, final_marking = inductive_miner.apply(trace_log)

gviz = vis_factory.apply(net, initial_marking, final_marking)
vis_factory.view(gviz)

```
It seems I should change the activity column to 'name'. Is there a way to not do so?

**Comment by Javert899** [comment]
Hi,

When you apply the Inductive Miner, you should provide a parameter specifying in which attribute the activity is written.

You could provide that (see http://pm4py.pads.rwth-aachen.de/documentation/process-discovery/classifiers/ ) using the following code (replace concept:name with the attribute containing the activity):

from pm4py.util import constants
parameters = {constants.PARAMETER_CONSTANT_ACTIVITY_KEY: "concept:name"}
net, initial_marking, final_marking = inductive_miner.apply(log, parameters=parameters)

**Comment by hadisotudeh** [comment]
Great. It worked.
