### ISSUE TITLE
Add option to deepcopy in log converison

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4py/pm4py-source#28]
Currently the log conversion only creates a new "enclosing" log object (e.g. EventLog) around the existing source log object.
In a way, one could see this as taking an alternative view on the log that acts as a source of the conversion.

It might be useful to add an option to the conversion (maybe through the parameter object?) that allows us to apply python's deep copy functionality.
This avoids side effects of changing the elements of either the source- or target log of the conversion.

**Comment by Javert899** [comment]
Hi,

The deepcopy option has been added (develop branch) as boolean parameter "DEEPCOPY" inside the log conversion factory
