### ISSUE TITLE
Refactoring SNA

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4py/pm4py-source#30]
SNA needs to be refactored a bit to follow the general factory method design

we should also consider implementing the "classical" metrics as described in the paper by v.d. Aalst et al (for example arbitrary distance SNA with fall factor beta)

**Comment by Javert899** [comment]
Hi,

The following metrics have been provided in the 'develop' branch:
- Handover of Work
- Working Together
- Subcontracting
- Similar Activities

The application takes into account a log object:

from pm4py.algo.enhancement.sna import factory as sna_factory
hw_values = sna_factory.apply(log, variant="handover")

And could be visualized through:

from pm4py.visualization.sna import factory as sna_vis_factory
gviz_hw_py = sna_vis_factory.apply(hw_values, variant="pyvis")
sna_vis_factory.view(gviz_hw_py, variant="pyvis")

**Comment by s-j-v-zelst** [comment]
nice
