### ISSUE TITLE
running_example.xes not loadable in ProM

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4py/pm4py-source#32]
It is somehow not possible to load the running_example.xes file in ProM.

Could this be due to loading / saving it through PM4Py, or is this not possible?

**Comment by Javert899** [comment]
Your fears are right.

Although we have full XES certification in both importing/exporting (meaning we pass all the tests), the exported log was not loadable on ProM for two issues:
- Timestamp exporting: in some cases the timestamps were exported without time zone. Now the behavior has been corrected.
-Globals exporting: the scope was missing in the export

The behavior has been corrected in the current release 1.0.17, just released on pip

**Comment by Javert899** [comment]
The test files have been exported again with the corrections that have been done.
