### ISSUE TITLE
Provide a conda package

### ISSUE THREAD

**Issue by fmannhardt** [pm4py/pm4py-source#34]
Thanks for the awesome work. I am working on a R port using the `reticulate` package, which provides a bridge between R and Python. At least on Windows this relies on a conda environment into which I can install pm4py using PIP, but I fear that this might lead to version conflicts if people already have installed conda packages that are required by other packages.

Would it be possible to provide a conda package for pm4py?

**Comment by Javert899** [comment]
Hi,

Thanks for this

It is not possible to provide such package for problems related to channel specifications in the meta.yaml for some packages (like for example pyvis and ciso8601)

The installation through PIP have been tested on some versions of Anaconda on both Windows and Linux, and no problems were reported, although the problem you underline may exist in some installations with a lot of extra packages installed.

The best thing I could do is to provide some "install_through_conda.bat" and "install_through_conda.sh" files that contains exactly the commands that need to be executed (e.g. conda install numpy, conda install cvxopt, conda install -c conda-forge ciso8601 ...), but those would be accessible only downloading the repository and manually executing them

**Comment by fmannhardt** [comment]
Thanks. To clarify, installing simply via `pip install` works fine as long as the dependencies install through `conda` are up-to-date or not installed at all. 

I will try to find a solution on the `R` side.
