### ISSUE TITLE
Provide `get_dataframe_from_log` as helper function

### ISSUE THREAD

**Issue by fmannhardt** [pm4py/pm4py-source#36]
I would like to convert an EventLog back to a Pandas DataFrame. Currently, I am using the method `get_dataframe_from_log` from `pandas_csv_exp.py` for this purpose.

I have two questions;
(1) Is this efficient? I saw that the method walks through the whole log to build a sequence from an EventLog, which seems to already be a sequence. 

(2) Would it be possible tot provide this method in some more generic helper/util package? It seems wrong to rely on the CSV exporter only to convert between EventLog and Pandas DataFrame.

**Comment by Javert899** [comment]
Hi, thanks for signaling

Actually, suggestion (2) was implemented in the 'develop' branch, moving get_dataframe_from_log utility into util df_from_log.

For (1), the fact is that the Event object is a Mapping object, not a dict, although it could be converted easily, that is the reason of the df = get_dataframe_from_log(log) row. So, we have to keep this behavior

**Comment by fmannhardt** [comment]
Thanks.
