### ISSUE TITLE
Limit `str` representation of TraceLog (and possibly EventLog)

### ISSUE THREAD

**Issue by fmannhardt** [pm4py/pm4py-source#38]
Currently when using the Python `str` function on a TraceLog it will print its entire contents. Even for small logs with can be a large amount of data. Often the string representation is used for debugging purposes and some tools cannot handle large amounts of text or it leads to performance issues.

Would you consider returning a shortened representation of the event log? I don't know abput Python but in R the data frames have a nice property of printing the head 10 elements and the tail 10 elements along with some information about the object.

**Comment by Javert899** [comment]
Hi, thanks for signaling

Actually, a more advanced log representation has been implemented in the 'develop' branch that prints:
- for the traces, only the first and last event
- for the logs, only the first and last trace

**Comment by fmannhardt** [comment]
Thanks. I should really be looking at the `develop` branch 👍
