### ISSUE TITLE
Inconsistent parameters `version` vs `variant`

### ISSUE THREAD

**Issue by fmannhardt** [pm4py/pm4py-source#39]
Upfront, thanks for the great work and sorry for nitpicking, this is only to improve/understand the API.

I noted that sometimes the factory `apply` methods take a `variant` parameter and sometimes a `version` parameter? Is this distinction on purpose and if so what is the difference?

**Comment by Javert899** [comment]
Hi,

Actually the 'version' parameter is present only in the 'pm4py.objects.conversion.log' factory

Therefore, I changed it to variant in the 'develop' branch

**Comment by fmannhardt** [comment]
Thanks

**Comment by fmannhardt** [comment]
Same issue in the Alpha miner:
https://github.com/pm4py/pm4py-source/blob/afa8d9d1eb1a87ee57a2ba3a75d7d292963590ff/pm4py/algo/discovery/alpha/factory.py#L14
