### ISSUE TITLE
PARAM_ACTIVITY_KEY used in evaluation is inconsistent with generic parameter

### ISSUE THREAD

**Issue by fmannhardt** [pm4py/pm4py-source#42]
The parameter used for the token replay in the evaluation module:
https://github.com/pm4py/pm4py-source/blob/afa8d9d1eb1a87ee57a2ba3a75d7d292963590ff/pm4py/evaluation/factory.py#L9
is inconsistent with the parameter defined globally here:
https://github.com/pm4py/pm4py-source/blob/master/pm4py/util/constants.py

It would simplify the API if this could be aligned.

**Comment by Javert899** [comment]
Hi,

Thanks for signaling. Actually, the problem has been fixed in the 'hotfixes' branch, and reported also in the 'develop' branch.

**Comment by fmannhardt** [comment]
I just tested this with the latest `develop` branch and it still gives an error when used with an event log that has a non-standard activity identifier. In fact, the parameter is not carried forward here:

https://github.com/pm4py/pm4py-source/blob/97f72523f15a3aca65215965af7dc7a0a528eb4b/pm4py/evaluation/factory.py#L74
