### ISSUE TITLE
Create PANDAS Log Object

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4py/pm4py-source#44]
There is some code that uses pandas as an underlying storage for event data.
This is mainly for performance reasons.

Somehow, there should be an encapsulation around this object, such that, in principle we can use it with any existing algorithm.

**Comment by Javert899** [comment]
Hi,

An improvement have been added to the 'develop' branch in the log_conversion.apply method, that converts a Pandas dataframe into an event logs prior to check if other types of conversions are needed.

The change is then propagated to the following algorithms:
-Alpha Miner
-Inductive Miner
-DFG
-Transition systems
-Conformance (alignments and token-based replay)
-Evaluation (general factory, replay fitness, precision, generalization)
-Petri net decoration

Moreover, Alpha Miner and Inductive Miner have been entitled to use the customized, faster, version for the extraction of the DFG directly from the Pandas dataframe.
