### ISSUE TITLE
Check Overall pythonic compliance

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4py/pm4py-source#5]
most of us have a java background.

some stuff might not yet be pythonic enough, e.g., we use CamelCasing instead of the_pythonic_way_of_naming_things in the /tests folder.
We *need* to fix this prior to the release, as this is of major importance for the adoption of the library!!!

**Comment by Javert899** [comment]
The following measures have been adopted for increasing the Pythonic compliance:
- eliminating camel case
- eliminating 2000 warnings and weak warnings signaled by the "Inspect code" feature in Pycharm
- substituting "while" cycle with Pythonic constructs
