### ISSUE TITLE
Log Animation

### ISSUE THREAD

**Issue by calla91** [pm4py/pm4py-source#53]
Hi everyone,
is a Log Animation function scheduled for future developments?
I was thinking about something like this R version:
https://github.com/fmannhardt/processanimateR

Thanks for the great work,
C.

**Comment by s-j-v-zelst** [comment]
Hi,

We might start developing this at the end of feb / beginnin of march.
Most likely we start with a visualization on top of directly follows graphs.

cheers,

Bas

**Comment by fmannhardt** [comment]
Feel free to re-use parts of the processanimateR code, the bulk of it is JavaScript so it might be possible to have a Python API towards it.
