### ISSUE TITLE
Add timeout parameter to long running operations

### ISSUE THREAD

**Issue by fmannhardt** [pm4py/pm4py-source#56]
A features request I just came across while running some experiments in which the precision calculation took forever. Would it be possible to add a timeout parameter to potentially long running operations? 

Not sure how to best to this in Python, but usually the cleanest way is to check from time to time in a loop within the long running operation.

**Comment by Javert899** [comment]
Hi,

Unfortunately, killing things/threads in Python is not as easy as killing it in Java,
but we will try to see if something could be done

**Comment by fmannhardt** [comment]
I realized. Trying to nicely kill it from R caused some errors.

Using a flag or timeout within the main loop of some computationally intensive method to stop gracefully is mostly the best option. I can have a go if I find time next week.
