### ISSUE TITLE
Filtering on attribute values

### ISSUE THREAD

**Issue by andionita** [pm4py/pm4py-source#57]
Hi, 

first of all, great work on building this process mining package! It's a great tool to play around with 
and helps understanding the process mining concepts even better.

So I have followed the [pm4py tutorial](http://pm4py.pads.rwth-aachen.de/documentation) and wanted to report a behavior that I find suspicious. I am using Python 3.6.5 on Linux and the project's master branch (1.0.23 / e0f408a).

It's about [filtering on attribute values](http://pm4py.pads.rwth-aachen.de/documentation/filtering-logs/). Consider the following snippet:

`xes_file_path = os.path.join('pm4py-source', 'tests', 'input_data', 'running-example.xes')`
`trace_log = xes_importer.import_log(xes_file_path)`
`trace_log = sorting.sort_timestamp(trace_log)`
`trace_log = attributes_filter.apply_auto_filter(trace_log, parameters = {constants.PARAMETER_CONSTANT_ATTRIBUTE_KEY: "org:resource", "decreasingFactor": 0.6})`

The resource count before applying the filter is 
[('Sara', 12), ('Mike', 11), ('Pete', 7), ('Ellen', 7), ('Sean', 3), ('Sue', 2)]

After applying the filter, a trace containing the resources (Mike, Mike, Sean, Sara, Ellen) is trimmed to (Mike, Mike, Sean, Sara). On the whole, the resource count becomes
[('Mike', 10), ('Sara', 9), ('Pete', 7), ('Ellen', 5), ('Sean', 3), ('Sue', 2)]

I would have expected that traces would have been trimmed completely of Sarah, Mike (11/12 > 0.6), Pete (7/11 > 0.6) and Ellen (7/7 > 0.6). How exactly is the trimming of traces based on the frequency of resources happening?

**Comment by Javert899** [comment]
Thanks for signaling.

The problem in attribute filter is that it looked at PARAMETER_CONSTANT_ACTIVITY_KEY in parameters instead of PARAMETER_CONSTANT_ATTRIBUTE_KEY

Problem solved in release 1.0.24
