### ISSUE TITLE
Conversion from Petri net into a BPMN

### ISSUE THREAD

**Issue by MatarFall** [pm4py/pm4py-source#60]
No module named 'pm4py.objects.conversion.petri_to_bpmn'.  It seems that this class doesn't exist!

**Comment by Javert899** [comment]
Hi,

You have to use the 'bpmnIntegration2' branch

You can move from the 'master' branch to the 'bpmnIntegration2' branch through the command:

git checkout bpmnIntegration2

**Comment by MatarFall** [comment]
It works. Thank You.
