### ISSUE TITLE
Alignment: TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by fmannhardt** [pm4py/pm4py-source#61]
Code to reproduce:
```
Python 3.7.2 (C:\Users\felixm\AppData\Local\Continuum\anaconda3\envs\r-reticulate\python.exe)
Reticulate 1.10.0.9004 REPL -- A Python interpreter in R.
>>> from pm4py.objects.log.importer.xes import factory as xes_importer
>>> log = xes_importer.import_log("C:/Process Mining/R/pm4py/../heur.xes")
>>> log
[{'attributes': {'concept:name': 'Case1.0'}, 'events': [{'concept:name': 'a', 'lifecycle:transition': 'complete', 'org:resource': 'UNDEFINED', 'time:timestamp': datetime.datetime(2010, 11, 4, 19, 57, 15, tzinfo=datetime.timezone.utc), 'concept:instance': '135', '.order': '135'}, '..', {'concept:name': 'e', 'lifecycle:transition': 'complete', 'org:resource': 'UNDEFINED', 'time:timestamp': datetime.datetime(2010, 11, 4, 19, 58, 15, tzinfo=datetime.timezone.utc), 'concept:instance': '136', '.order': '136'}]}, '....', {'attributes': {'concept:name': 'Case6.0'}, 'events': [{'concept:name': 'a', 'lifecycle:transition': 'complete', 'org:resource': 'UNDEFINED', 'time:timestamp': datetime.datetime(2010, 11, 4, 19, 57, 15, tzinfo=datetime.timezone.utc), 'concept:instance': '137', '.order': '137'}, '..', {'concept:name': 'e', 'lifecycle:transition': 'complete', 'org:resource': 'UNDEFINED', 'time:timestamp': datetime.datetime(2010, 11, 4, 19, 59, 15, tzinfo=datetime.timezone.utc), 'concept:instance': '139', '.order': '139'}]}]
>>> import pm4py
>>> from pm4py.algo.conformance.alignments import factory as align_factory
>>> 
>>> import os
>>> from pm4py.objects.petri.importer import pnml as pnml_importer
>>> 
>>> net, initial_marking, final_marking = pnml_importer.import_net("C:/Process Mining/R/pm4py/../heur.pnml")
>>> 
>>> alignments = align_factory.apply_log(log, net, initial_marking, final_marking)
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

This occurs with the following Petri net and log of the Heuristics Miner example:
[heur.zip](https://github.com/pm4py/pm4py-source/files/2881765/heur.zip)

This is the full stack trace:
```
  TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

Detailed traceback: 
  File "C:\Users\felixm\AppData\Local\CONTIN~1\ANACON~1\envs\R-RETI~1\lib\site-packages\pm4py\algo\conformance\alignments\factory.py", line 35, in apply
    final_marking, parameters, version)
  File "C:\Users\felixm\AppData\Local\CONTIN~1\ANACON~1\envs\R-RETI~1\lib\site-packages\pm4py\algo\conformance\alignments\factory.py", line 147, in apply_log
    log))
  File "C:\Users\felixm\AppData\Local\CONTIN~1\ANACON~1\envs\R-RETI~1\lib\site-packages\pm4py\algo\conformance\alignments\factory.py", line 146, in <lambda>
    version=version),
  File "C:\Users\felixm\AppData\Local\CONTIN~1\ANACON~1\envs\R-RETI~1\lib\site-packages\pm4py\algo\conformance\alignments\factory.py", line 79, in apply_trace
    return VERSIONS[version](trace, petri_net, initial_marking, final_marking, parameters)
  File "C:\Users\felixm\AppData\Local\CONTIN~1\ANACON~1\envs\R-RETI~1\lib\site-packages\pm4py\algo\conformance\alignments\versions\state_equation_a_star.py", line 120, in apply
    alignments.utils.SKIP, ret_tuple_as_trans_desc=ret_tuple_as_trans_desc)
  File "C:\Users\felixm\AppData\Local\CONTIN~1\ANACON~1\envs\R-RETI~1\lib\site-packages\pm4py\algo\conformance\alignments\versions\state_equation_a_star.py", line 141, in apply_sync_prod
    ret_tuple_as_trans_desc=ret_tuple_as_trans_desc)
  File "C:\Users\felixm\AppData\Local\CONTIN~1\ANACON~1\envs\R-RETI~1\lib\site-packages\pm4py\algo\conformance\alignments\versions\state_equation_a_star.py", line 159, in __search
    tp = SearchTuple(curr.g + h, curr.g, h, curr.m, curr.p, curr.t, x, __trust_solution(x))
```

Could this be an issue with the LP solver?

**Comment by Javert899** [comment]
Hi,

The Petri net looks a sound workflow net to my eye, but the initial marking is set as empty, and that is not correct.

**Comment by fmannhardt** [comment]
I see, there was an issue with my exporting code and now there are both markings in the file.
Anyway, still the same error so it seems something to be wrong with some other part.

This is the correct Petri net:
[heur_v2.zip](https://github.com/pm4py/pm4py-source/files/2884165/heur_v2.zip)

Note that alignments do not require sound Workflow nets as input, should work for any Petri net. It is just not guaranteed to finish ;)

**Comment by Javert899** [comment]
Actual implementation in PM4Py, that is based on an Heuristic based on resolving the marking equation, requires at least relaxed soundness ..

Obviously, other implementations could be considered in future ;)

**Comment by fmannhardt** [comment]
Yes, that is that I meant. Non relaxed sound ones cannot be aligned by definition.
Anyway, there seems to be something else wrong regarding the example I uploaded.

**Comment by fmannhardt** [comment]
Was this fixed?

**Comment by Javert899** [comment]
Unfortunately there is no much we can do on the current version if the net is not sound

In some time from now, a version that is able to do alignments on accepting Petri nets, although with a much larger number of states evaluated, will be worked

See issue #62

**Comment by fmannhardt** [comment]
Did you have a look at the last files I uploaded:
https://github.com/pm4py/pm4py-source/files/2884165/heur_v2.zip

This has the correct initial and final marking. it is not a sound workflow net, but definitely a relaxed sound Petri net as required by alignments --- at least in its original definition. 
Does the PM4PY implementation only work for sound workflow nets?

**Comment by s-j-v-zelst** [comment]
Hi @fmannhardt,

I have looked at this together with @Javert899 
Minor side note, alignments can actually be computed on easy sound WF nets, which are non-relaxed ;-)

Anyways, the problem was, that I didn't check in the code if a solution existed for the heuristic.
Clearly, if there is no solution, the heuristic should be set to infinity (or MAX INT).
At the moment, the heuristic was None and then the addition of the heuristic to the cost traveled so far was breaking.

From a theoretical perspective, this implies that the code was only able to handle sound WF nets indeed.
We have released this fix in 1.1.1

**Comment by fmannhardt** [comment]
Thanks. All those definitions, what was `easy sound` again? ;)

**Comment by s-j-v-zelst** [comment]
there just has to exist a path from the initial marking to the final marking (easy sound).

relaxed sound is something along the lines of we are able to enable each transition from the initial marking and after firing such transition we can still reach the final marking.

**Comment by fmannhardt** [comment]
Oh, then `easy sound` is what I call `relaxed sound` for Data Petri nets. :-)
