### ISSUE TITLE
Error converting event stream to log

### ISSUE THREAD

**Issue by 1dhiman** [pm4py/pm4py-source#63]
`log = conversion_factory.apply(event_stream)`

`KeyError: 'case:concept:name'`

Please see full [code](https://www.kaggle.com/dhimananubhav/process-mining-w-python)

**Comment by Javert899** [comment]
Hi,

You have to specify the column that acts as case ID in the parameters

Example script:

from pm4py.objects.log.importer.csv import factory as csv_importer
from pm4py.objects.conversion.log import factory as conversion_factory
from pm4py.util import constants

stream = csv_importer.apply("C:\\road_traffic.csv")
log = conversion_factory.apply(stream, parameters={constants.PARAMETER_CONSTANT_CASEID_KEY: "case"})
