### ISSUE TITLE
Sets of states or single states for transition edges of reachability graph of petri nets?

### ISSUE THREAD

**Issue by jwllee** [pm4py/pm4py-source#64]
`curr_state` and `next_state` are particular transition system states. 
https://github.com/pm4py/pm4py-source/blob/12162f78f31f3f7c327899a00848168de5eff9c6/pm4py/objects/petri/reachability_graph.py#L56
then, a transition edge is constructed from the current and next states:
https://github.com/pm4py/pm4py-source/blob/12162f78f31f3f7c327899a00848168de5eff9c6/pm4py/objects/transition_system/utils.py#L21
But the to and from state definitions for transitions in the `TransitionSystem` class suggest that they should be sets:
https://github.com/pm4py/pm4py-source/blob/12162f78f31f3f7c327899a00848168de5eff9c6/pm4py/objects/transition_system/transition_system.py#L39-L40

Which one should it be? I am not sure if defining a transition from one set of states to another is useful. But this definitely is a potential bug.

**Comment by Javert899** [comment]
Thanks for signaling. The issue has been solved in release 1.1.3

**Comment by jwllee** [comment]
Sorry, should have checked the commit more carefully... But since `from_state` and `to_state` are no longer sets, perhaps should add back setter methods?

**Comment by Javert899** [comment]
Hi!

Thanks, your code will be released in the next PM4Py version :)

Thanks for the contribution and have a nice Sunday
