### ISSUE TITLE
petri nets importer / exporter does not follow standardized factory pattern

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4py/pm4py-source#66]
see title :-)

If I have time (which I usually don't) I will try to fix this.
If you want to fix it (Ale) you are more than welcome 👍 🥇

**Comment by Javert899** [comment]
Hi,

The issue has been resolved in the 'develop' branch, moving the importer/exporter into the classic factory method structure.

For compatibility reasons, the old classes are still there (calling the new ones) with the @deprecated
