### ISSUE TITLE
Intuitive CSV Import

### ISSUE THREAD

**Issue by lsabi** [pm4py/pm4py-source#70]
Hi,

If one is using the csv import functionality and needs to import a dataframe, apply some conversions/filtering and then convert it into an event log, one has to import two different modules.

My question is, wouldn't be more intuitive to have all the import functionalities within the same module?

Thanks

**Comment by Javert899** [comment]
To solve your problem, while leaving door open for different dataframe managers than Pandas, the following methods have been added in the 'develop' branch to the factory pm4py.objects.log.importer.csv.factory:

- import_dataframe_from_path
- import_dataframe_from_path_wo_timeconversion
- import_dataframe_from_csv_string
- convert_dataframe_to_stream

So, the enhancement you suggest has been performed in the 'develop' branch. Take a look at that

**Comment by lsabi** [comment]
My bad, didn't see that. Any idea/estimate when the develop branch will be merged into the production?

Thanks

**Comment by Javert899** [comment]
Let's say in two/three weeks!

Sincerely
Alessandro

Il gio 11 apr 2019, 12:14 lsabi <notifications@github.com> ha scritto:

**Comment by lsabi** [comment]
Great. I'm closing the issue then.

Thanks.
