### ISSUE TITLE
Problem with Heuristics Miner: Key Error when getting heuristics net, depending on threshold

### ISSUE THREAD

**Issue by carvalhomb** [pm4py/pm4py-source#71]
Trying to use the Heuristics Miner functionality, I came across a KeyError when trying to get an heuristics net. The error depends on the dependency threshold set.

Code to reproduce the error below, with (zipped) example log attached.

```
from pm4py.objects.log.importer.csv import factory as csv_importer
from pm4py.objects.conversion.log import factory as conversion_factory

event_stream = csv_importer.import_event_stream("testlog.csv") 
log = conversion_factory.apply(event_stream)

# This works
heu_net = heuristics_miner.apply_heu(log, parameters={"dependency_thresh": 0.99})
gviz = hn_vis_factory.apply(heu_net)
hn_vis_factory.view(gviz)

# This gives KeyError
heu_net = heuristics_miner.apply_heu(log, parameters={"dependency_thresh": 0.9})
gviz = hn_vis_factory.apply(heu_net)
hn_vis_factory.view(gviz)
```
[testlog.zip](https://github.com/pm4py/pm4py-source/files/3072502/testlog.zip)

**Comment by Luttik** [comment]
I am also having this KeyError exception.
The offending method (for me) is at `calculate_loops_length_two` in `pm4py.objects.heuristics_net.node.py`.
Where `dfg_matrix[n1][n2]` throws the error.

**Comment by Luttik** [comment]
After browsing through the source code I found that dfg_matrix is used in an unsafe manner throughout the project.

**Comment by Luttik** [comment]
To fix this I suggest indexing `dfg_matrix` with tuples so `dfg_matrix[n1,n2]` then you can either fix this by calling `dfg_matrix.get((n1, n2), 0)` to safely get the values or you can use collections.abc.MutableMatrix to overwrite `__get__` so you can still call `dfg_matrix[n1, n2]` and get a default value if none is present.

**Comment by Javert899** [comment]
Thank you both for signaling the bug and the suggestions

I will try to solve the issue and release an hotfix release before Monday :)

**Comment by Luttik** [comment]
@Javert899 That sounds great. Thanks.

**Comment by Javert899** [comment]
The signaled issue was corrected in hotfix release 1.1.10 (docker images are being rebuilt from now)

Thanks again for signaling

**Comment by Luttik** [comment]
@Javert899 Great. It seems to be working 👍

**Comment by carvalhomb** [comment]
Excellent, for me it is also working :) Closing the issue.
