### ISSUE TITLE
Heuristics miner graph shows duplicated arcs

### ISSUE THREAD

**Issue by carvalhomb** [pm4py/pm4py-source#74]
When generating a Heuristics Net graph, I noticed that in some cases there are duplicated arcs, that is, more than one arc to/from the same nodes, with the same values. 

This can be fixed by passing the parameter "strict"=True to the class pydotplus.Dot (visualization/heuristics_net/versions/pydotplus.py, line 84). Maybe "strict" could be a parameter to be passed on as a parameter to the heuristics_net visualization factory?

**Comment by Javert899** [comment]
Hi, thanks for signaling and suggesting a mitigation, that was applied in the 'develop' branch

**Comment by carvalhomb** [comment]
Excellent, thank you for answering so quickly! Closing the issue.
