### ISSUE TITLE
(Bug: Alignment) best_worst_cost will not consider the MODEL_COST_FUNCTION from parameter

### ISSUE THREAD

**Issue by lvzheqi** [pm4py/pm4py-source#75]
best_worst_cost will not consider the MODEL_COST_FUNCTION from parameter,
because PRAM_TRACE_COST_FUNCION is None, it always calls the "construct_standard_cost_function" and uses the default cost.

when the model-move and log-move have different cost, it is problematic by fitness computing.

**Comment by Javert899** [comment]
Are you considering latest version?

**Comment by Javert899** [comment]
See commit https://github.com/pm4py/pm4py-source/commit/1669369caefbb28bb9493079c242cba14172edd7

**Comment by lvzheqi** [comment]
yep, I am not working on the latest version. It seems good for
best-worst-cost.
 But fitness will be problematic when the model-move and log-move have
different cost, right?

Javert899 <notifications@github.com> 于2019年4月15日周一 下午5:38写道：

**Comment by Javert899** [comment]
Here it depends on how the fitness value is calculated :)

For this let me know if you think it is wrong and eventually how to fix that!

**Comment by lvzheqi** [comment]
For me, I think, fitness = 1 - align["cost"]) / ( len(log[index]) *
MODEL_MOVE_COST + best_worst_cost * LOG_MOVE_COST).
I'm not so sure...
MODEL_MOVE_COST and LOG_MOVE_COST maybe need to extract from parameters

Javert899 <notifications@github.com> 于2019年4月15日周一 下午5:53写道：

**Comment by lvzheqi** [comment]
And I have a technic problem by installation requirements in windows. Could
you help me?
I want to run the data on the computer in the uni, because it takes too
long, to run the data in my own computer.
So I try to setup the environment.
I download visual studio and the system-operation is 64.
But it always shows this error, when it installs "pyarrow".
[image: image.png]
[image: image.png]


吕哲奇 <lvzheqi@gmail.com> 于2019年4月15日周一 下午5:59写道：

**Comment by Javert899** [comment]
Tomorrow I can come after lunch :)

**Comment by lvzheqi** [comment]
Super, thanks! 😄

Javert899 <notifications@github.com> 于2019年4月15日周一 下午6:26写道：

**Comment by Javert899** [comment]
Keep note that in the 'develop' branch alignments are got much faster in comparison to the 'stable' release (nothing approach-wise but a lot of tricks, they are 40% faster in each condition now, not considering variants grouping that on some logs can speed up things of 100x)

**Comment by lvzheqi** [comment]
Yep, I see. Thanks.

Javert899 <notifications@github.com> 于2019年4月15日周一 下午6:28写道：

**Comment by Javert899** [comment]
After code exchange between me and lvzheqi I would say this issue is definitely closed :)
