### ISSUE TITLE
Quotation marks in activity names produce malformed graphviz file

### ISSUE THREAD

**Issue by alexsee** [pm4py/pm4py-source#77]
I tried to visualize the `log_IEEE.xes.gz` event log using the heuristics miner using the following code:
```
from pm4py.algo.discovery.heuristics import factory as heuristics_miner
from pm4py.objects.log.importer.xes import factory as xes_importer
from pm4py.visualization.petrinet import factory as vis_factory

log = xes_importer.import_log('log_IEEE.xes.gz', {"timestamp_sort": True})
net, initial_marking, final_marking = heuristics_miner.apply(log, parameters={"dependency_thresh": 0.9, "and_measure_thresh": 0.1, "loops_length_two_thresh": 0.9})

gviz = vis_factory.apply(net, initial_marking, final_marking)
vis_factory.view(gviz)
```
It looks like the activity names include a quotation mark which is not correctly formatted into the graphviz format. I got the following exception:
```
Error: ...\AppData\Local\Temp\tmprtekkhy0.gv: syntax error in line 377 near '.'
```
which corresponds to
```
splace_in_SRM:" Change was Transmitted_SRM": In Transfer to Execution Syst._0 -> hid_89
```
I guess the quotation marks need to be escaped here.

**Comment by Javert899** [comment]
Hi,

Sorry for the issue. Actually, it is a problem of GraphViz that do not accept quotation characters in node names.

A workaround for the issue has been deployed in the develop branch, where for the following objects:
- Petri net
- DFG
- Transition systems
The name of the node is set to the hash.
