### ISSUE TITLE
Wrong Code Documentation

### ISSUE THREAD

**Issue by lsabi** [pm4py/pm4py-source#79]
Hi,

In the comment for the function **apply_heu_dfg** in the file **pm4py/algo/discovery/heuristics/versions/classic.py**, it is written that the function returns three values (net (Petri net), im (Initial marking) and fm (Final marking)), but it returns only one (heu_net).

I'm checking the master branch, so it may be that the development branch is correct.

**Comment by lsabi** [comment]
Same for the function **apply_heu** in the same file

**Comment by Javert899** [comment]
Problem resolved in the current release
