### ISSUE TITLE
ET Conformance vs OnProm Results

### ISSUE THREAD

**Issue by lsabi** [pm4py/pm4py-source#83]
I was checking the code of the ET Conformance function and I found the comment

"At the moment, the precision value is different from the one provided by the ProM plug-in,
although the implementation seems to follow the paper concept"

Is there any news why it returns a different precision value?

Also, does the pm4py's precision remain scaled (or keeps the same gap) with respect to the OnProm version? E.g., even if results are different between pm4py and OnProm, given trace A, that is x times more compliant than trace B in pm4py, does it hold also on OnProm?

Thanks

**Comment by Javert899** [comment]
The results are as follows. Resume: for models extracted with the Alpha Miner, where no invisible transitions need to be traversed, the two ETConformance approaches produce very similar numbers.
For models extracted with the Inductive Miner, where invisible transitions need to be traversed, the ETConformance approach in PM4Py is able to reach out a vastly larger number of transitions, thanks to the efficient token-based replay.


\begin{table}[ht]
\footnotesize
\centering
\begin{tabular}{|l|cc|cc|}
\hline
{\bf Log} & {\bf Alpha ETC PM4Py} & {\bf Alpha ETC P6} & {\bf Ind ETC PM4Py} & {\bf Ind ETC P6} \\
\hline
repairEx & 0.98 & 0.98 & 0.22 & 0.17 \\
reviewing & 0.74 & 0.74 & 0.18 & 0.18 \\
bpic2017 & 0.61 & 0.65 & 0.76 & 0.76 \\
receipt & 0.37 & 0.37 & 0.12 & 0.07 \\
roadtraff & 0.76 & 0.63 & 0.49 & 0.07 \\
sepsis & 0.05 & 0.44 & 0.16 & 0.05 \\
Billing & 0.49 & 0.36 & 0.47 & 0.09 \\
\hline
\end{tabular}
\caption{Comparison between the ET Conformance implementation in PM4Py (using the token-based replay to detect activated transitions) and in ProM6 on models extracted by the Alpha Miner and by the Inductive Miner implementations in PM4Py.}
\label{tab:etconformancecomparison}
\end{table}


\begin{table}
\tiny
\centering
\begin{tabular}{|p{28mm}|c|p{28mm}p{28mm}|}
\hline
{\bf Prefix} & {\bf Occurrences of the prefix} & {\bf Reflected tasks} & {\bf Activated transitions} \\
\hline
Create~Fine & 150370 & Send~Fine ,Payment ,Insert~Date~Appeal~to~Prefecture ,Appeal~to~Judge & Receive~Result~Appeal~from~Prefecture ,Payment ,Notify~Result~Appeal~to~Offender ,Appeal~to~Judge ,Add~penalty ,Send~for~Credit~Collection ,Send~Appeal~to~Prefecture ,Send~Fine ,Insert~Date~Appeal~to~Prefecture ,Insert~Fine~Notification \\
\hline
Create~Fine, Send~Fine & 83007 & Payment ,Insert~Fine~Notification ,Send~Appeal~to~Prefecture ,Insert~Date~Appeal~to~Prefecture ,Appeal~to~Judge & Receive~Result~Appeal~from~Prefecture ,Payment ,Notify~Result~Appeal~to~Offender ,Appeal~to~Judge ,Add~penalty ,Send~for~Credit~Collection ,Send~Appeal~to~Prefecture ,Send~Fine ,Insert~Date~Appeal~to~Prefecture ,Insert~Fine~Notification \\
\hline
Create~Fine, Send~Fine, Insert~Fine~Notification & 79594 & Receive~Result~Appeal~from~Prefecture ,Payment ,Send~Appeal~to~Prefecture ,Insert~Date~Appeal~to~Prefecture ,Appeal~to~Judge ,Add~penalty & Receive~Result~Appeal~from~Prefecture ,Payment ,Notify~Result~Appeal~to~Offender ,Appeal~to~Judge ,Add~penalty ,Send~for~Credit~Collection ,Send~Appeal~to~Prefecture ,Send~Fine ,Insert~Date~Appeal~to~Prefecture ,Insert~Fine~Notification \\
\hline
Create~Fine, Send~Fine, Insert~Fine~Notification, Add~penalty & 72101 & Receive~Result~Appeal~from~Prefecture ,Payment ,Notify~Result~Appeal~to~Offender ,Send~for~Credit~Collection ,Insert~Date~Appeal~to~Prefecture ,Appeal~to~Judge & Receive~Result~Appeal~from~Prefecture ,Payment ,Notify~Result~Appeal~to~Offender ,Appeal~to~Judge ,Add~penalty ,Send~for~Credit~Collection ,Send~Appeal~to~Prefecture ,Send~Fine ,Insert~Date~Appeal~to~Prefecture ,Insert~Fine~Notification \\
\hline
Create~Fine, Send~Fine, Insert~Fine~Notification, Add~penalty, Payment & 5359 & Payment ,Insert~Date~Appeal~to~Prefecture ,Appeal~to~Judge ,Send~for~Credit~Collection & Receive~Result~Appeal~from~Prefecture ,Payment ,Notify~Result~Appeal~to~Offender ,Appeal~to~Judge ,Add~penalty ,Send~for~Credit~Collection ,Send~Appeal~to~Prefecture ,Send~Fine ,Insert~Date~Appeal~to~Prefecture ,Insert~Fine~Notification \\
\hline
\end{tabular}
\caption{Comparison for reflected tasks and activated transitions for some prefixes of the Road Traffic Fine Management log and the model extracted from it using the Inductive Miner in PM4Py.}
\label{tab:roadtrafficprefixes}
\end{table}
