### ISSUE TITLE
Alpha Miner's "__check_is_unrelated" is faulty

### ISSUE THREAD

**Issue by acardos** [pm4py/pm4py-source#84]
# Description
The function `__check_is_unrelated` in Alpha Miner does not check for every possible combination of items if they are in a relation.

## Problem: zip_longest
It uses [`zip_longest`](https://docs.python.org/3.0/library/itertools.html#itertools.zip_longest) which combines every item of set 1 with the item of set 2 at the same position.
This leads a somewhat random behaviour, because the order in a set is random and a relation between two items might be missed.

What we need here is [`product`](https://docs.python.org/3.0/library/itertools.html#itertools.product), to combine every item of set 1 with every item of set 2. 

# Example:
Assume 'B' and 'C' are in a parallel relation and the itemsets `{'C'})` and `{'E', 'B'})` are passed to `__check_is_unrelated`.
But it will not detect the relation, becuase it is only checked if 'C' and 'E' are related. 
`zip_longest`  produces: `[('C', 'E'), (None, 'B')]`.
`product` produces: `[('C', 'E'), ('C', 'B')]` and so also 'C' and 'B' will be checked for a relation.

**Comment by Javert899** [comment]
Thanks for your contribution.

The pull request has been merged!
