### ISSUE TITLE
data frame to event log conversion is wrong

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4py/pm4py-source#87]
the data frame to event log conversion seems to return an event stream obejct rather than a event log object.

**Comment by Javert899** [comment]
Seemingly debunked:

SCRIPT
from pm4py.objects.log.adapters.pandas import csv_import_adapter
from pm4py.objects.conversion.log import factory as log_conv_factory

df = csv_import_adapter.import_dataframe_from_path("C:\\running-example.csv")
print(type(df))
log = log_conv_factory.apply(df)
print(type(log))

OUTPUT
<class 'pandas.core.frame.DataFrame'>
<class 'pm4py.objects.log.log.EventLog'>

**Comment by s-j-v-zelst** [comment]
indeed, I double checked the code, it was a false alarm.
