### ISSUE TITLE
Black Boxes in Petri Net Visuals 

### ISSUE THREAD

**Issue by ackjake** [pm4py/pm4py-source#88]
What do the black boxes in petri nets represent in pm4py? They appear to be unlabeled events that occur within the petri nets. I haven't seen this notation in other petri net documentations, what do they represent?

**Comment by Javert899** [comment]
Yes, you are right. They are invisible transitions, not corresponding to any activity in the log. In some process discovery algorithms (as the inductive miner) they are used much

**Comment by s-j-v-zelst** [comment]
@ackjake Indeed, as @Javert899 indicates, these transitions are invisible.
The use of such transitions is two-fold. Typically, these transitions are used to allow us to skip certain business activities. Secondly, they can be used as 'invisible routing constructs'. For example, if a process starts with two/three/four activities that can happen concurrent. We typically initiate the concurrency using an invisible transition (when modeling the process as a (sound) WF Net). 

Typically a petri net with in visible labels is defined as a quadruple N=(P,T,F,l), where l is either 1.) a partial function T -> A (where A represents the universe of activity labels), or, 2.) a total function T -> A + {t} (read + as the set union and t as 'tau' i.e. the observable label.

Hope this helps!
