### ISSUE TITLE
Naming Inconsistency(ies) Objects / Visualizatoin

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4py/pm4py-source#91]
I observed a naming inconsistency in the visualization of petri nets.
The object subpackage is named 'petri'
for visualization it is named petrinet.

> Fix: copy visualization folder to a new folder called petri. Deprecate the current petrinet folder (no removal, we need to be backward compatible, we will remove in a later phase).

In general, consistency needs to be checked. We use petrinet, heuristics_net, process_tree, decisiontree (we have to either always use _ or never)

**Comment by fit-alessandro-berti** [comment]
Let's do that for the packages of the future. Renaming them now would kill thousands of scripts :)
