### ISSUE TITLE
Graphviz executables not found

### ISSUE THREAD

**Issue by bcourbon** [pm4py/pm4py-source#96]
Hi,

I have an issue with graphviz in PM4Py.

I'm using Python 3.7.1.
I've followed all the installation steps :
- install Visual Studio
- install Graphviz
- add `C:\Program Files (x86)\Graphviz2.38\bin` to my system path
- `pip install pm4py`

Everything went fine.

Then I tried to run the following code : 
`from pm4py.algo.discovery.alpha import factory as alpha_miner`
`from pm4py.objects.log.importer.xes import factory as xes_importer`
`from pm4py.visualization.petrinet import factory as vis_factory`
`log = xes_importer.import_log('myfile.xes')`
`net, initial_marking, final_marking = alpha_miner.apply(log)`
`gviz = vis_factory.apply(net, initial_marking, final_marking)`
`vis_factory.view(gviz)`

Everything went fine except the last line raising the following error : 
`ExecutableNotFound: failed to execute ['dot', '-Tpng', '-O', 'tmpess6uujg.gv'], make sure the Graphviz executables are on your systems' PATH`

I do have `'GRAPHVIZ': 'C:\\Program Files (x86)\\Graphviz2.38\\bin'` when I print `os.environ`, then I don't understand.

Any help?

Best,

Benoit

**Comment by s-j-v-zelst** [comment]
Hi Benoit,

Thanks for using the PM4Py library!
You could try to add C:\Program Files (x86)\Graphviz2.38\bin\dot.exe to System Path as well, maybe this helps?

cheers,

bas

**Comment by bcourbon** [comment]
Hi,

You welcome PM4Py looks like a very useful tool.

Unfortunately adding the line to the path this does not help either.

Cheers

Benoit
