### ISSUE TITLE
Consider upgrading matplotlib to version 3

### ISSUE THREAD

**Issue by dmpe** [pm4py/pm4py-source#98]
Hi there, 
Please could you consider upgrading matplotlib in https://github.com/pm4py/pm4py-source/blob/master/requirements.txt to something newer ?

Thanks.

**Comment by Javert899** [comment]
Thanks for signaling.

Some tests will be done to check the actual compatibility with later versions. If so, the release will be upgraded accordingly.

**Comment by Javert899** [comment]
Hi,

The update has been applied. Except from some small problems with SNA visualization, everything is fine also with Matplotlib 3.1

**Comment by dmpe** [comment]
Thanks! @Javert899
